spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: notes_admin
    password: notes_secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect