spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: notes_admin
    password: notes_secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

app:
  jwt:
    secret: 422Hj7MmbEKtmeJZcGN6qs40jAkXra8Few+8+S2Wrqs=
    access-token-expiration: 900000       # 15 minutes in ms
    refresh-token-expiration: 2592000000  # 30 days in ms